module.exports = [
  { abbrev: 'AK', full: 'Alaska' },
  { abbrev: 'AL', full: 'Alabama' },
  { abbrev: 'AR', full: 'Arkansas' },
  { abbrev: 'AS', full: 'American Samoa' },
  { abbrev: 'AZ', full: 'Arizona' },
  { abbrev: 'CA', full: 'California' },
  { abbrev: 'CO', full: 'Colorado' },
  { abbrev: 'CT', full: 'Connecticut' },
  { abbrev: 'DC', full: 'District of Columbia' },
  { abbrev: 'DE', full: 'Delaware' },
  { abbrev: 'FL', full: 'Florida' },
  { abbrev: 'GA', full: 'Georgia' },
  { abbrev: 'GU', full: 'Guam' },
  { abbrev: 'HI', full: 'Hawaii' },
  { abbrev: 'IA', full: 'Iowa' },
  { abbrev: 'ID', full: 'Idaho' },
  { abbrev: 'IL', full: 'Illinois' },
  { abbrev: 'IN', full: 'Indiana' },
  { abbrev: 'KS', full: 'Kansas' },
  { abbrev: 'KY', full: 'Kentucky' },
  { abbrev: 'LA', full: 'Louisiana' },
  { abbrev: 'MA', full: 'Massachusetts' },
  { abbrev: 'MD', full: 'Maryland' },
  { abbrev: 'ME', full: 'Maine' },
  { abbrev: 'MI', full: 'Michigan' },
  { abbrev: 'MN', full: 'Minnesota' },
  { abbrev: 'MO', full: 'Missouri' },
  { abbrev: 'MP', full: 'Northern Mariana Islands' },
  { abbrev: 'MS', full: 'Mississippi' },
  { abbrev: 'MT', full: 'Montana' },
  { abbrev: 'NC', full: 'North Carolina' },
  { abbrev: 'ND', full: 'North Dakota' },
  { abbrev: 'NE', full: 'Nebraska' },
  { abbrev: 'NH', full: 'New Hampshire' },
  { abbrev: 'NJ', full: 'New Jersey' },
  { abbrev: 'NM', full: 'New Mexico' },
  { abbrev: 'NV', full: 'Nevada' },
  { abbrev: 'NY', full: 'New York' },
  { abbrev: 'OH', full: 'Ohio' },
  { abbrev: 'OK', full: 'Oklahoma' },
  { abbrev: 'OR', full: 'Oregon' },
  { abbrev: 'PA', full: 'Pennsylvania' },
  { abbrev: 'PR', full: 'Puerto Rico' },
  { abbrev: 'RI', full: 'Rhode island' },
  { abbrev: 'SC', full: 'South Carolina' },
  { abbrev: 'SD', full: 'South Dakota' },
  { abbrev: 'TN', full: 'Tennessee' },
  { abbrev: 'TX', full: 'Texas' },
  { abbrev: 'UT', full: 'Utah' },
  { abbrev: 'VA', full: 'Virginia' },
  { abbrev: 'VI', full: 'Virgin Islands' },
  { abbrev: 'VT', full: 'Vermont' },
  { abbrev: 'WA', full: 'Washington' },
  { abbrev: 'WI', full: 'Wisconsin' },
  { abbrev: 'WV', full: 'West Virginia' },
  { abbrev: 'WY', full: 'Wyoming' },
];
