export const {
    entry,
    login,
    signup,
    passReset,
    passChange,
    passFormChange,
    userFormChange,
    donationFailure,
  } = require('./formSubmit'),
  { logOut } = require('./logOut'),
  { loadUser } = require('./loadUser'),
  { clearForm } = require('./clearForm'),
  { setTokens } = require('./setTokens'),
  { activation } = require('./activation'),
  { deleteUser } = require('./deleteUser'),
  { updateUser } = require('./updateUser'),
  { refreshToken } = require('./refreshToken'),
  { substituteSrc } = require('./substituteSrc'),
  { transformPolData } = require('./transformPolData');
