const {
    lock,
    open,
    prune,
    rattle,
    accrue,
    attest,
    verify,
    confirm,
    activate,
    generate,
    transfer,
  } = require('./utils'),
  { find } = require('./find'),
  { create } = require('./create'),
  { remove } = require('./remove'),
  { update } = require('./update'),
  { contact } = require('./contact'),
  { identify } = require('./identify'),
  { deem, certify, empower, promote } = require('./privileges');

module.exports = {
  transfer,
  generate,
  activate,
  identify,
  confirm,
  contact,
  certify,
  empower,
  promote,
  accrue,
  attest,
  create,
  rattle,
  remove,
  update,
  verify,
  prune,
  lock,
  open,
  deem,
  find,
};
